import type { ColorToken, ModeColorToken } from "./color-swatches";

export const BRAND_COLOR_TOKENS: ColorToken[] = [
  {
    name: "Static white",
    token: "--color-static-white",
    value: "#ffffff",
    usage: "Non-inverting white for icons and text that must remain white in dark mode.",
  },
  {
    name: "White",
    token: "--color-white",
    value: "#ffffff",
    usage: "Light-mode white surface value. This token inverts in dark mode.",
  },
  {
    name: "Surface",
    token: "--color-surface",
    value: "#ffffff",
    usage: "Default card, modal, and framed component surface.",
  },
  {
    name: "Cream",
    token: "--color-cream",
    value: "#fafaf9",
    usage: "Warm neutral used for calm page areas and product backgrounds.",
  },
  {
    name: "Background cream",
    token: "--color-background-cream",
    value: "#ffffff",
    usage: "Main app background token used by global page styles.",
  },
  {
    name: "Gray light",
    token: "--color-gray-light",
    value: "#e7e5e4",
    usage: "Subtle dividers, disabled fills, and quiet interface boundaries.",
  },
  {
    name: "Black",
    token: "--color-black",
    value: "#292524",
    usage: "Primary dark neutral for light-mode text and icon contrast.",
  },
  {
    name: "Mizen blue",
    token: "--color-blue",
    value: "#18a1f7",
    usage: "Primary brand color for actions, focus states, and active controls.",
  },
  {
    name: "Primary blue",
    token: "--color-primary-blue",
    value: "#18a1f7",
    usage: "Alias used by focus rings and core primary interaction styles.",
  },
  {
    name: "Blue light",
    token: "--color-blue-light",
    value: "#e6f0ff",
    usage: "Soft selected state and pale blue supporting surfaces.",
  },
  {
    name: "Mint",
    token: "--color-mint",
    value: "#d3f4f0",
    usage: "Fresh supporting color for saved-state context and light illustrations.",
  },
  {
    name: "Navy",
    token: "--color-navy",
    value: "#034497",
    usage: "Deep blue accent for stronger contrast and brand depth.",
  },
  {
    name: "Red",
    token: "--color-red",
    value: "#fe4703",
    usage: "Destructive, critical, and urgent feedback color used sparingly.",
  },
  {
    name: "Olive",
    token: "--color-olive",
    value: "#6e9f00",
    usage: "Food-adjacent accent for produce, success-adjacent states, and illustration.",
  },
  {
    name: "Green",
    token: "--color-green",
    value: "#1a8521",
    usage: "Positive state color for successful actions and confirmations.",
  },
  {
    name: "Wheat",
    token: "--color-wheat",
    value: "#fdeecc",
    usage: "Warm food surface for empty states, recipe moments, and light brand support.",
  },
  {
    name: "Orange",
    token: "--color-orange",
    value: "#fb9c00",
    usage: "Warning and attention accent used in small doses.",
  },
  {
    name: "Text heading",
    token: "--color-text-heading",
    value: "#1c1917",
    usage: "Primary heading and high-emphasis text color in light mode.",
  },
  {
    name: "Text body",
    token: "--color-text-body",
    value: "#333333",
    usage: "Default body copy color in light mode.",
  },
  {
    name: "Text muted",
    token: "--color-text-muted",
    value: "#78716c",
    usage: "Secondary copy, metadata, placeholders, and supporting labels.",
  },
  {
    name: "Border light",
    token: "--color-border-light",
    value: "#e7e5e4",
    usage: "Primary border token for product chrome and grouped surfaces.",
  },
  {
    name: "Overlay",
    token: "--color-overlay",
    value: "rgba(0, 0, 0, 0.75)",
    usage: "Dimmed page layer behind modal and drawer surfaces.",
    displayColor: "rgba(0, 0, 0, 0.75)",
  },
];

export const MODE_COLOR_TOKENS: ModeColorToken[] = [
  {
    token: "--color-background-cream",
    usage: "Main application background.",
    light: "#ffffff",
    dark: "#171412",
  },
  {
    token: "--color-surface",
    usage: "Cards, popovers, dialogs, and framed component surfaces.",
    light: "#ffffff",
    dark: "#1c1918",
  },
  {
    token: "--color-cream",
    usage: "Warm neutral page and component fill.",
    light: "#fafaf9",
    dark: "#292524",
  },
  {
    token: "--color-white",
    usage: "Inverting surface token. Use static white when the value must stay white.",
    light: "#ffffff",
    dark: "#292524",
  },
  {
    token: "--color-black",
    usage: "Inverting high-contrast neutral.",
    light: "#292524",
    dark: "#fafaf9",
  },
  {
    token: "--color-gray-light",
    usage: "Subtle fills and disabled state backgrounds.",
    light: "#e7e5e4",
    dark: "#3a3633",
  },
  {
    token: "--color-text-heading",
    usage: "Heading and high-emphasis copy.",
    light: "#1c1917",
    dark: "#fafaf9",
  },
  {
    token: "--color-text-body",
    usage: "Default reading text.",
    light: "#333333",
    dark: "#d6d3d1",
  },
  {
    token: "--color-text-muted",
    usage: "Secondary text, metadata, and low-emphasis labels.",
    light: "#78716c",
    dark: "#a8a29e",
  },
  {
    token: "--color-border-light",
    usage: "Primary border color for app surfaces.",
    light: "#e7e5e4",
    dark: "#3a3633",
  },
  {
    token: "--color-blue-light",
    usage: "Soft blue fill for selected or supportive states.",
    light: "#e6f0ff",
    dark: "#1e293b",
  },
  {
    token: "--color-green",
    usage: "Success and positive state color.",
    light: "#1a8521",
    dark: "#2ecc55",
  },
  {
    token: "--color-olive",
    usage: "Food-adjacent accent color.",
    light: "#6e9f00",
    dark: "#8ec420",
  },
  {
    token: "--color-dark-surface",
    usage: "Dark-only surface used where the product needs a stronger dark foundation.",
    light: "transparent",
    dark: "#0b0a0a",
  },
  {
    token: "--color-blue",
    usage: "Primary brand blue. This stays stable across modes.",
    light: "#18a1f7",
    dark: "#18a1f7",
  },
  {
    token: "--color-red",
    usage: "Destructive and urgent accent. This stays stable across modes.",
    light: "#fe4703",
    dark: "#fe4703",
  },
  {
    token: "--color-mint",
    usage: "Fresh supporting accent. This stays stable across modes.",
    light: "#d3f4f0",
    dark: "#d3f4f0",
  },
  {
    token: "--color-wheat",
    usage: "Warm recipe accent. This stays stable across modes.",
    light: "#fdeecc",
    dark: "#fdeecc",
  },
  {
    token: "--color-orange",
    usage: "Warning and attention accent. This stays stable across modes.",
    light: "#fb9c00",
    dark: "#fb9c00",
  },
];

export const SEMANTIC_COLOR_TOKENS: ModeColorToken[] = [
  {
    token: "--background",
    usage: "shadcn background alias mapped to Tailwind as bg-background.",
    light: "oklch(1 0 0)",
    dark: "oklch(0.145 0 0)",
    lightDisplayColor: "#ffffff",
    darkDisplayColor: "#242424",
  },
  {
    token: "--foreground",
    usage: "Default foreground alias mapped to Tailwind as text-foreground.",
    light: "oklch(0.145 0 0)",
    dark: "oklch(0.922 0 0)",
    lightDisplayColor: "#242424",
    darkDisplayColor: "#e4e4e4",
  },
  {
    token: "--card",
    usage: "Card surface alias.",
    light: "oklch(1 0 0)",
    dark: "oklch(0.178 0 0)",
    lightDisplayColor: "#ffffff",
    darkDisplayColor: "#2b2b2b",
  },
  {
    token: "--card-foreground",
    usage: "Card text and icon foreground alias.",
    light: "oklch(0.145 0 0)",
    dark: "oklch(0.922 0 0)",
    lightDisplayColor: "#242424",
    darkDisplayColor: "#e4e4e4",
  },
  {
    token: "--popover",
    usage: "Popover and menu surface alias.",
    light: "oklch(1 0 0)",
    dark: "oklch(0.178 0 0)",
    lightDisplayColor: "#ffffff",
    darkDisplayColor: "#2b2b2b",
  },
  {
    token: "--popover-foreground",
    usage: "Popover and menu foreground alias.",
    light: "oklch(0.145 0 0)",
    dark: "oklch(0.922 0 0)",
    lightDisplayColor: "#242424",
    darkDisplayColor: "#e4e4e4",
  },
  {
    token: "--primary",
    usage: "Primary foreground and filled control alias from shadcn primitives.",
    light: "oklch(0.205 0 0)",
    dark: "oklch(0.922 0 0)",
    lightDisplayColor: "#333333",
    darkDisplayColor: "#e4e4e4",
  },
  {
    token: "--primary-foreground",
    usage: "Foreground color used on primary filled controls.",
    light: "oklch(0.985 0 0)",
    dark: "oklch(0.205 0 0)",
    lightDisplayColor: "#fbfbfb",
    darkDisplayColor: "#333333",
  },
  {
    token: "--secondary",
    usage: "Secondary button and low-emphasis filled surface alias.",
    light: "oklch(0.97 0 0)",
    dark: "oklch(0.264 0 0)",
    lightDisplayColor: "#f7f7f7",
    darkDisplayColor: "#424242",
  },
  {
    token: "--secondary-foreground",
    usage: "Foreground color used on secondary filled controls.",
    light: "oklch(0.205 0 0)",
    dark: "oklch(0.922 0 0)",
    lightDisplayColor: "#333333",
    darkDisplayColor: "#e4e4e4",
  },
  {
    token: "--muted",
    usage: "Muted background alias for quieter blocks and disabled-adjacent surfaces.",
    light: "oklch(0.97 0 0)",
    dark: "oklch(0.264 0 0)",
    lightDisplayColor: "#f7f7f7",
    darkDisplayColor: "#424242",
  },
  {
    token: "--muted-foreground",
    usage: "Foreground alias for muted and supporting text.",
    light: "oklch(0.556 0 0)",
    dark: "oklch(0.556 0 0)",
    lightDisplayColor: "#737373",
    darkDisplayColor: "#737373",
  },
  {
    token: "--accent",
    usage: "Hover and active surface alias used by shadcn primitives.",
    light: "oklch(0.97 0 0)",
    dark: "oklch(0.264 0 0)",
    lightDisplayColor: "#f7f7f7",
    darkDisplayColor: "#424242",
  },
  {
    token: "--accent-foreground",
    usage: "Foreground alias for accent, hover, and active surfaces.",
    light: "oklch(0.205 0 0)",
    dark: "oklch(0.922 0 0)",
    lightDisplayColor: "#333333",
    darkDisplayColor: "#e4e4e4",
  },
  {
    token: "--destructive",
    usage: "Destructive primitive alias.",
    light: "oklch(0.577 0.245 27.325)",
    dark: "oklch(0.577 0.245 27.325)",
    lightDisplayColor: "#e7000b",
    darkDisplayColor: "#e7000b",
  },
  {
    token: "--border",
    usage: "Default shadcn border alias.",
    light: "oklch(0.922 0 0)",
    dark: "oklch(0.32 0 0)",
    lightDisplayColor: "#e4e4e4",
    darkDisplayColor: "#505050",
  },
  {
    token: "--input",
    usage: "Input border and input chrome alias.",
    light: "oklch(0.922 0 0)",
    dark: "oklch(0.32 0 0)",
    lightDisplayColor: "#e4e4e4",
    darkDisplayColor: "#505050",
  },
  {
    token: "--ring",
    usage: "Focus ring alias. It resolves to Mizen primary blue in both modes.",
    light: "var(--color-primary-blue)",
    dark: "var(--color-primary-blue)",
    lightDisplayColor: "#18a1f7",
    darkDisplayColor: "#18a1f7",
  },
];
