// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngfisvbqchujuqvtogvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nZmlzdmJxY2h1anVxdnRvZ3Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzUyMTEsImV4cCI6MjA2NDU1MTIxMX0.oEjoJ00Gfn_42nqzAvXATPFpf1IncV29_Lh2Lvpd3t0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);